from __future__ import annotations

import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

if __package__ in {None, ""}:
    sys.path.append(str(Path(__file__).resolve().parents[1]))

from src.config import PROJECT_ROOT, load_config
from src.sensor_layouts import apply_sensor_layout
from src.supplementary_study_utils import (
    copy_final_figures_to_root_and_paper,
    load_calibrated_params,
    load_models_for_sim,
    load_sonderborg_processed,
    save_figure,
    simulate_from_dataframe,
    evaluate_models_on_sim,
    write_latex_table,
)
from src.utils import ensure_dir


SELECTED_MODELS = {
    "GRU-MSE",
    "Transformer-MSE",
    "PI-LSTM",
    "Proposed PI-GNN-GRU-v3 accuracy_mode",
    "Proposed PI-GNN-GRU-v3 balanced_mode",
}


def _select_regime_block(df: pd.DataFrame, regime: str, max_steps: int) -> pd.DataFrame:
    data = df.sort_values("timestamp").reset_index(drop=True).copy()
    heat = pd.to_numeric(data["heat_load_kw"], errors="coerce")
    q20, q40, q60 = heat.quantile([0.20, 0.40, 0.60]).to_list()
    month = data["timestamp"].dt.month
    if regime == "winter_high_load":
        mask = month.isin([12, 1, 2]) | (heat >= q60)
    elif regime == "shoulder_medium_load":
        mask = month.isin([3, 4, 10, 11]) | ((heat >= q20) & (heat <= q60))
    else:
        mask = month.isin([5, 6, 7, 8, 9]) | (heat <= q20)
    selected = data.loc[mask].copy()
    if len(selected) < max(48, max_steps // 3):
        selected = data.sort_values("heat_load_kw", ascending=(regime != "winter_high_load")).head(max_steps).copy()
        selected = selected.sort_values("timestamp")
    return selected.head(max_steps).reset_index(drop=True)


def run_seasonal_generalization() -> None:
    config = load_config()
    ensure_dir(PROJECT_ROOT / "results")
    ensure_dir(PROJECT_ROOT / "figures" / "final")
    params = load_calibrated_params()
    df = load_sonderborg_processed(config)
    max_steps = int(config["dataset"]["n_scenarios_full"] * config["system"]["horizon_h"] * 3600 / config["system"]["dt_s"])
    max_steps = max(220, min(max_steps, 768))

    winter_df = _select_regime_block(df, "winter_high_load", max_steps)
    shoulder_df = _select_regime_block(df, "shoulder_medium_load", max_steps)
    summer_df = _select_regime_block(df, "low_load_optional", max_steps)
    regimes = {
        "winter_high_load": winter_df,
        "shoulder_medium_load": shoulder_df,
        "low_load_optional": summer_df,
    }

    base_sim = simulate_from_dataframe(winter_df, config, params)
    base_sensors = apply_sensor_layout(base_sim, "S4_five_sensors", config)
    trained, base_loaders = load_models_for_sim(base_sim, base_sensors, config)
    stats = base_loaders["train_ds"].stats

    all_rows: list[pd.DataFrame] = []
    split_rows = []
    payload_by_regime: dict[str, dict[str, dict[str, np.ndarray]]] = {}
    sim_by_regime = {}
    for regime, regime_df in regimes.items():
        sim = simulate_from_dataframe(regime_df, config, params)
        sensors = apply_sensor_layout(sim, "S4_five_sensors", config)
        result, payloads = evaluate_models_on_sim(
            sim,
            config,
            trained,
            stats,
            layout="S4_five_sensors",
            sensors_override=sensors,
            case_label="winter_calibrated_model_to_regime",
            regime=regime,
            note=(
                "Seasonal regimes are derived from real Sonderborg operating data by timestamp/heat-load quantiles. "
                "Distributed states are generated by the calibrated simulator."
            ),
            selected_models=SELECTED_MODELS,
        )
        all_rows.append(result)
        payload_by_regime[regime] = payloads
        sim_by_regime[regime] = sim
        split_rows.append(
            {
                "regime": regime,
                "n_steps": len(regime_df),
                "start": str(regime_df["timestamp"].iloc[0]) if len(regime_df) else "",
                "end": str(regime_df["timestamp"].iloc[-1]) if len(regime_df) else "",
                "mean_heat_load_kW": float(pd.to_numeric(regime_df["heat_load_kw"], errors="coerce").mean()),
                "mean_supply_temp_C": float(pd.to_numeric(regime_df["supply_temp_C"], errors="coerce").mean()),
                "mean_return_temp_C": float(pd.to_numeric(regime_df["return_temp_C"], errors="coerce").mean()),
                "state_type": "real_measured_node",
                "note": "Regime summary uses real measured plant-level Sonderborg data.",
            }
        )

    seasonal = pd.concat(all_rows, ignore_index=True)
    seasonal.to_csv(PROJECT_ROOT / "results" / "seasonal_generalization.csv", index=False)
    seasonal.to_csv(PROJECT_ROOT / "results" / "seasonal_generalization_improved.csv", index=False)
    summary = pd.DataFrame(split_rows)
    summary.to_csv(PROJECT_ROOT / "results" / "seasonal_split_summary.csv", index=False)
    summary.to_csv(PROJECT_ROOT / "results" / "seasonal_split_summary_improved.csv", index=False)
    table_cols = [
        "regime",
        "model",
        "supply_RMSE_C",
        "return_RMSE_C",
        "heat_loss_error_percent",
        "energy_balance_residual_percent",
        "thermal_delay_error_min",
        "pressure_drop_error_percent",
    ]
    write_latex_table(
        seasonal[[c for c in table_cols if c in seasonal.columns]],
        PROJECT_ROOT / "paper" / "tables" / "table_seasonal_generalization.tex",
        "Seasonal generalization under heat-load regimes. Seasonal regimes use real Sonderborg operating data; distributed hidden states are calibrated-simulator outputs.",
        "tab:seasonal_generalization",
    )

    _plot_regime_distributions(regimes)
    _plot_regime_metrics(seasonal)
    _plot_regime_summary(seasonal)
    _plot_temperature_reconstruction(sim_by_regime, payload_by_regime)
    copy_final_figures_to_root_and_paper()
    print("Seasonal generalization supplementary study completed.")


def _plot_regime_distributions(regimes: dict[str, pd.DataFrame]) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(11.5, 3.6))
    values = [pd.to_numeric(df["heat_load_kw"], errors="coerce") / 1000.0 for df in regimes.values()]
    axes[0].boxplot(values, labels=[k.replace("_", "\n") for k in regimes])
    axes[0].set_ylabel("Heat load (MW)")
    values_supply = [pd.to_numeric(df["supply_temp_C"], errors="coerce") for df in regimes.values()]
    axes[1].boxplot(values_supply, labels=[k.replace("_", "\n") for k in regimes])
    axes[1].set_ylabel("Supply temperature ($^\\circ$C)")
    values_return = [pd.to_numeric(df["return_temp_C"], errors="coerce") for df in regimes.values()]
    axes[2].boxplot(values_return, labels=[k.replace("_", "\n") for k in regimes])
    axes[2].set_ylabel("Return temperature ($^\\circ$C)")
    for ax in axes:
        ax.tick_params(axis="x", labelsize=7)
        ax.grid(True, axis="y", alpha=0.25)
    fig.suptitle("Seasonal regimes from real Sonderborg operating data")
    save_figure(fig, "fig_seasonal_heat_load_regimes")


def _plot_regime_metrics(df: pd.DataFrame) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(11.0, 4.2))
    if df.empty:
        for ax in axes:
            ax.text(0.5, 0.5, "No seasonal data", ha="center", va="center")
            ax.axis("off")
    else:
        compact = df.copy()
        compact["model_short"] = compact["model"].str.replace("Proposed PI-GNN-GRU-v3 ", "PI-GNN-v3 ", regex=False)
        pivot = compact.pivot_table(index="model_short", columns="regime", values="supply_RMSE_C", aggfunc="mean")
        pivot.plot(kind="bar", ax=axes[0], width=0.82)
        axes[0].set_ylabel("Supply RMSE ($^\\circ$C)")
        axes[0].set_title("Direct thermal accuracy by regime")
        pivot2 = compact.pivot_table(index="model_short", columns="regime", values="heat_loss_error_percent", aggfunc="mean")
        pivot2.plot(kind="bar", ax=axes[1], width=0.82)
        axes[1].set_ylabel("Heat-loss error (%)")
        axes[1].set_title("Heat-loss consistency by regime")
        for ax in axes:
            ax.tick_params(axis="x", labelrotation=25, labelsize=7)
            ax.grid(True, axis="y", alpha=0.25)
            ax.legend(fontsize=6)
    fig.suptitle("Seasonal generalization under different heat-load regimes")
    save_figure(fig, "fig_seasonal_generalization_metrics")


def _plot_regime_summary(df: pd.DataFrame) -> None:
    metrics = [
        ("supply_RMSE_C", "Supply RMSE ($^\\circ$C)"),
        ("return_RMSE_C", "Return RMSE ($^\\circ$C)"),
        ("heat_loss_error_percent", "Heat-loss error (%)"),
        ("energy_balance_residual_percent", "Energy residual (%)"),
        ("thermal_delay_error_min", "Delay error (min)"),
    ]
    fig, axes = plt.subplots(1, len(metrics), figsize=(14.0, 3.7))
    compact = df[df["model"].astype(str).str.contains("GRU-MSE|Transformer-MSE|PI-GNN-GRU-v3 balanced_mode", regex=True)].copy()
    compact["model_short"] = compact["model"].str.replace("Proposed PI-GNN-GRU-v3 ", "PI-GNN-v3 ", regex=False)
    for ax, (metric, ylabel) in zip(axes, metrics):
        if compact.empty or metric not in compact:
            ax.text(0.5, 0.5, "not available", ha="center", va="center")
            ax.axis("off")
            continue
        pivot = compact.pivot_table(index="regime", columns="model_short", values=metric, aggfunc="mean")
        pivot.plot(kind="bar", ax=ax, width=0.8, legend=False)
        ax.set_ylabel(ylabel)
        ax.tick_params(axis="x", labelrotation=25, labelsize=7)
        ax.grid(True, axis="y", alpha=0.25)
    axes[-1].legend(fontsize=6, loc="best")
    fig.suptitle("Seasonal generalization summary: real regimes, simulator-assisted distributed states")
    save_figure(fig, "fig_seasonal_generalization_summary")


def _plot_temperature_reconstruction(
    sim_by_regime: dict[str, dict[str, np.ndarray]],
    payload_by_regime: dict[str, dict[str, dict[str, np.ndarray]]],
) -> None:
    regimes = [r for r in ["winter_high_load", "shoulder_medium_load"] if r in payload_by_regime]
    fig, axes = plt.subplots(1, max(1, len(regimes)), figsize=(10.5, 3.8), squeeze=False)
    for ax, regime in zip(axes.ravel(), regimes):
        sim = sim_by_regime[regime]
        payloads = payload_by_regime[regime]
        if not payloads:
            continue
        x_km = np.asarray(sim["x_m"], dtype=float) / 1000.0
        ref = payloads.get("Proposed PI-GNN-GRU-v3 balanced_mode") or next(iter(payloads.values()))
        heat = np.asarray(ref["heat_load_kw"]).reshape(-1)
        idx = int(np.nanargmax(heat)) if heat.size else 0
        true = np.asarray(ref["true"]).reshape(-1, len(x_km), 4)[idx, :, 0]
        ax.plot(x_km, true, color="black", lw=2.0, label="calibrated simulator hidden state")
        for model in ["GRU-MSE", "Transformer-MSE", "Proposed PI-GNN-GRU-v3 balanced_mode"]:
            if model in payloads:
                pred = np.asarray(payloads[model]["pred"]).reshape(-1, len(x_km), 4)[idx, :, 0]
                ax.plot(x_km, pred, lw=1.4, label=model.replace("Proposed PI-GNN-GRU-v3 ", "PI-GNN-v3 "))
        ax.set_xlabel("Distance (km)")
        ax.set_ylabel("Supply temperature ($^\\circ$C)")
        ax.set_title(regime.replace("_", " "))
        ax.grid(True, alpha=0.25)
        ax.legend(fontsize=6)
    fig.suptitle("Seasonal temperature reconstruction; hidden labels are calibrated-simulator outputs")
    save_figure(fig, "fig_seasonal_temperature_reconstruction")


if __name__ == "__main__":
    run_seasonal_generalization()
