from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

if __package__ in {None, ""}:
    sys.path.append(str(Path(__file__).resolve().parents[1]))

from src.robustness_operational_utils import (
    PROJECT_ROOT,
    TABLES_DIR,
    add_safe_claim_columns,
    compact_model_name,
    first_existing,
    safe_numeric,
    save_grouped_bar_figure,
    write_json,
    write_latex_table,
)


def run() -> None:
    source = first_existing(["seasonal_generalization.csv", "seasonal_generalization_improved.csv"])
    if source.empty:
        out = pd.DataFrame([{"status": "not run", "note": "Seasonal source results were not available."}])
    else:
        out = source.copy()
        out["model_short"] = out["model"].map(compact_model_name)
        if "regime" not in out.columns:
            out["regime"] = "not specified"
        if {"supply_RMSE_C", "return_RMSE_C"}.issubset(out.columns):
            out["thermal_RMSE_sum_C"] = safe_numeric(out["supply_RMSE_C"]) + safe_numeric(out["return_RMSE_C"])
        base = out.groupby("model", as_index=False)["thermal_RMSE_sum_C"].min() if "thermal_RMSE_sum_C" in out else pd.DataFrame()
        if not base.empty:
            base = base.rename(columns={"thermal_RMSE_sum_C": "best_regime_thermal_RMSE_sum_C"})
            out = out.merge(base, on="model", how="left")
            out["performance_degradation_percent"] = (
                (safe_numeric(out["thermal_RMSE_sum_C"]) - safe_numeric(out["best_regime_thermal_RMSE_sum_C"]))
                / safe_numeric(out["best_regime_thermal_RMSE_sum_C"]).clip(lower=1e-9)
                * 100.0
            )
        out = add_safe_claim_columns(
            out,
            "real_measured_node + calibrated_simulator + simulator_assisted_hidden_state",
            "Seasonal/load-regime analysis uses real Sonderborg operating regimes and calibrated-simulator hidden states.",
            "The seasonal/load-regime analysis evaluates robustness under different district-heating operating regimes rather than claiming universal seasonal generalization.",
        )
    out.to_csv(PROJECT_ROOT / "results" / "seasonal_load_regime_metrics.csv", index=False)

    processed = PROJECT_ROOT / "data" / "processed" / "sonderborg_processed.csv"
    assumptions = {
        "source": "Derived from existing seasonal_generalization.csv and real Sonderborg processed data when available.",
        "regime_definition": "Low/shoulder/medium/high regimes follow the existing timestamp and heat-load quantile split.",
        "safe_interpretation": "Regime robustness test, not proof of universal seasonal generalization.",
    }
    if processed.exists():
        df = pd.read_csv(processed, usecols=["heat_load_kw"])
        q = df["heat_load_kw"].quantile([0.2, 0.4, 0.6, 0.8]).to_dict()
        assumptions["heat_load_quantiles_kW"] = {str(k): float(v) for k, v in q.items()}
    write_json("seasonal_load_regime_assumptions.json", assumptions)

    table_cols = [
        "regime",
        "model_short",
        "supply_RMSE_C",
        "return_RMSE_C",
        "heat_loss_error_percent",
        "energy_balance_residual_percent",
        "pressure_drop_error_percent",
        "performance_degradation_percent",
    ]
    write_latex_table(
        out[[c for c in table_cols if c in out.columns]],
        TABLES_DIR / "table_seasonal_load_regime_performance.tex",
        "Seasonal/load-regime performance. Regimes are derived from real Sonderborg operation; distributed hidden states are generated by the calibrated simulator.",
        "tab:seasonal_load_regime_performance",
    )
    plot(out)


def plot(df: pd.DataFrame) -> None:
    selected = df[df.get("model_short", "").astype(str).isin(["GRU", "Transformer", "PI-LSTM", "PI-GNN-v3 acc.", "PI-GNN-v3 bal."])].copy() if not df.empty else df
    save_grouped_bar_figure(
        "fig_seasonal_load_regime_performance",
        [
            {"title": "Supply temperature", "data": selected, "category": "regime", "series": "model_short", "value": "supply_RMSE_C", "ylabel": "RMSE (C)"},
            {"title": "Return temperature", "data": selected, "category": "regime", "series": "model_short", "value": "return_RMSE_C", "ylabel": "RMSE (C)"},
            {"title": "Heat-loss consistency", "data": selected, "category": "regime", "series": "model_short", "value": "heat_loss_error_percent", "ylabel": "Error (%)"},
        ],
        title="Seasonal/load-regime robustness from real Sonderborg profiles",
    )


if __name__ == "__main__":
    run()
